export const API = {
  ADDSOCIALGREETING: '/addSocialGreeting',
  ADDSOCIALLINK: '/addSocialLink',
  UPLOADICON: '/uploadIconAndGetURL',
  SCANPDF: '/scanpdf',
  UPDATEUSERPROFILE: '/updateProfile',
  GETUSERPROFILE: '/userProfile',
  GETLATEXFROMUSERPROFILE: '/getTexFromProfile',
  GETPDFFROMLATEX: '/convert-tex',
  SAVETEX: '/saveResume',
  GETTEXCONTENT: '/getTexContent',
  MAP_ID_TO_EMAIL: '/mapEmailToId',
  GET_ID_FROM_EMAIL: '/getIdFromEmail',
  DELETE_SOCIAL_LINK: '/deleteSocialLink',
  GET_PDF_FROM_EMAIL: '/getPdfFromEmail',
  GET_BENTO_FROM_PORTFOLIO_DATA: '/bento',
  SAVE_BENTO: '/saveBento',
  GET_BENTO_WEBSITE: '/getSavedBento',
  GET_BENTO_FROM_EMAIL: '/getBentoFromEmail',
};
