export const API = {
  ADDSOCIALGREETING: '/addSocialGreeting',
  ADDSOCIALLINK: '/addSocialLink',
  UPLOADICON: '/uploadIconAndGetURL',
  SCANPDF: '/scanpdf',
  UPDATEUSERPROFILE: '/updateProfile',
  GETUSERPROFILE: '/userProfile',
  GETLATEXFROMUSERPROFILE: '/getTexFromProfile',
  GETPDFFROMLATEX: '/convert-tex',
  SAVETEX: '/saveResume',
  GETTEXCONTENT: '/getTexContent',
  MAP_ID_TO_EMAIL: '/mapEmailToId',
  GET_ID_FROM_EMAIL: '/getIdFromEmail',
  DELETE_SOCIAL_LINK: '/deleteSocialLink',
};
