export interface SocialMediaBaseUrl {
  baseURL: string;
  value: string;
}

export const POPULAR_SOCIAL_MEDIA_BASE_URLS: SocialMediaBaseUrl[] = [
  { baseURL: 'https://facebook.com/', value: 'facebook' },
  { baseURL: 'https://www.facebook.com/', value: 'facebook' },
  { baseURL: 'https://x.com/', value: 'x' },
  { baseURL: 'https://www.x.com/', value: 'x' },
  { baseURL: 'https://instagram.com/', value: 'instagram' },
  { baseURL: 'https://www.instagram.com/', value: 'instagram' },
  { baseURL: 'https://linkedin.com/', value: 'linkedin' },
  { baseURL: 'https://www.linkedin.com/', value: 'linkedin' },
  { baseURL: 'https://github.com/', value: 'github' },
  { baseURL: 'https://www.github.com/', value: 'github' },
  { baseURL: 'https://youtube.com/', value: 'youtube' },
  { baseURL: 'https://www.youtube.com/', value: 'youtube' },
  { baseURL: 'https://t.me/', value: 'telegram' },
  { baseURL: 'https://www.t.me/', value: 'telegram' },
  { baseURL: 'https://snapchat.com/', value: 'snapchat' },
  { baseURL: 'https://www.snapchat.com/', value: 'snapchat' },
  { baseURL: 'https://pinterest.com/', value: 'pinterest' },
  { baseURL: 'https://www.pinterest.com/', value: 'pinterest' },
  { baseURL: 'https://reddit.com/', value: 'reddit' },
  { baseURL: 'https://www.reddit.com/', value: 'reddit' },
  { baseURL: 'https://discord.com/', value: 'discord' },
  { baseURL: 'https://www.discord.com/', value: 'discord' },
  { baseURL: 'https://medium.com/', value: 'medium' },
  { baseURL: 'https://www.medium.com/', value: 'medium' },
  { baseURL: 'https://threads.net/', value: 'threads' },
  { baseURL: 'https://www.threads.net/', value: 'threads' },
  { baseURL: 'https://mastodon.social/', value: 'mastodon' },
  { baseURL: 'https://www.mastodon.social/', value: 'mastodon' },
  { baseURL: 'https://dribbble.com/', value: 'dribbble' },
  { baseURL: 'https://www.dribbble.com/', value: 'dribbble' },
  { baseURL: 'https://behance.net/', value: 'behance' },
  { baseURL: 'https://www.behance.net/', value: 'behance' },
  { baseURL: 'https://tiktok.com/', value: 'tiktok' },
  { baseURL: 'https://www.tiktok.com/', value: 'tiktok' },
  { baseURL: 'https://soundcloud.com/', value: 'soundcloud' },
  { baseURL: 'https://www.soundcloud.com/', value: 'soundcloud' },
  { baseURL: 'https://spotify.com/', value: 'spotify' },
  { baseURL: 'https://www.spotify.com/', value: 'spotify' },
  { baseURL: 'https://quora.com/', value: 'quora' },
  { baseURL: 'https://www.quora.com/', value: 'quora' },
];
